dist: trusty
language: node_js
language: node_js
node_js:
  - '12'
install: npm install
script:
- npm test
- npm run docs:build
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: docs
  github_token: $GITHUB_TOKEN
  keep_history: true
  fqdn: endb.js.org
  on:
    branch: master